name: Deploy to GitHub Pages

# 1. Pipeline Trigger
# Triggers on a Pull Request to the main branch
on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - closed
  workflow_dispatch: 

jobs:
  build-and-deploy:
    # Run only on PR creation or update. Deployment (merge) is handled by the final step's 'if' condition.
    if: github.event_name != 'pull_request' || github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    
    # 2. Environment Variables
    env:
      NODE_VERSION: '20' 
      # Set DIST_DIR based on your angular.json "outputPath": "dist/portfolio"
      DIST_DIR: 'dist/portfolio/browser' # Use 'dist/portfolio/browser' for Angular application builds
                                        # Note: If your build process results in just 'dist/portfolio', use that instead. 
                                        # 'dist/<project-name>/browser' is common for Angular 17+ app builds.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # 4. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # 5. Build the Angular Application
      - name: Build Angular App for GH Pages 🛠️
        # This uses the 'deploy:gh' script defined in your package.json
        run: npm run deploy:gh 

      # 6. Deploy to GitHub Pages
      # This step ONLY runs after the PR is successfully merged (closed event AND merged=true)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIST_DIR }}
          publish_branch: gh-pages # Deploys to the gh-pages branch